#### Competition ####
broadcast-competition-start: true
broadcast-competition-end: true
broadcast-competition-winner: true


#### REWARDS ####

# Set whether or not to get custom fish outside of competitions
competition-only: false

# Display who caught a reward
display-who-caught: true

# Reward name's prefix and suffix
reward-prefix: ""
reward-suffix: ""


#### FISH ####

# Recommended value: 1.35 - Will favor the minimum fish length twice as much as maximum fish length.
# Changing this by even just .01 will have a noticeable difference
# The weight for the fish length
fish-length-weight: 1.35

# Display the fish's length in the item lore
display-fish-lengh: true


#### RARITY MODIFIERS ####

# Allow rarity modifiers
enable-modifiers: true

# Price increase for modifiers is addition
price-increase-addition: true

# Price increase for modifiers multiplication
price-increase-multiplication: false

# Modifier's prefix and suffix
modifier-prefix: "&8[&r"
modifier-suffix: "&8] &6-&r "

