#### Competition ####

# Broadcast the competition start and end
broadcast-competition-start: true
broadcast-competition-end: true

# Displays the competition winners
broadcast-competition-winner: true

# Display the top number of players in a competition - Max is 10
players-displayed: 5

# Minimum amount of people to participate in a competition
minimum-fishers: 1

# Run a fishing competition at the server's local times
competition-run-times:
  - '00:00'
  - '03:00'
  - '06:00'
  - '09:00'
  - '12:00'
  - '15:00'
  - '18:00'
  - '21:00'

# How long the auto run competitions will last in minutes
competition-duration: 15

# The boss bar title for a fishing competition - (%time% will be replaced with the actual time left in seconds and minutes)
timebar-title: "&b&lFishing Contest &r[%time% left]"


#### REWARDS ####

# If there is a yaml file in the rewards folder matching a name on this list it will be loaded - (Leave off the extension)
enabled-reward-configs:
  - "fish"

# Set whether or not to get custom fish outside of competitions
competition-only: true

# Display who caught a reward
display-who-caught: true

# Reward name's prefix and suffix - (%display-name% will be replaced with the actual reward's name
reward-names: "%display-name%"


#### FISH ####

# Recommended value: 1.35 - Will favor the minimum fish length twice as much as maximum fish length.
# Changing this by even just .01 will have a noticeable difference
# The weight for the fish length
fish-length-weight: 1.35

# Display the fish's length in the item lore
display-fish-lengh: true


#### RARITY MODIFIERS ####

# Allow reward modifiers
enable-modifiers: true

# Modifier's prefix and suffix - (%display-name% will be replaced with the actual modifier's name)
modifier-names: "&8[&r%display-name%&8] &6-&r "


#### SHOP ####

shop-name: "FishingPlus Shop"

# This price multiplier is multiplied by the length of the fish to get the price
price-multiplier: .5

# Config version - DO NOT CHANGE #
config-version: "1.0.0"
